import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { App } from './app/app';

import { SpAtAccordionItem } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-accordion-item';
import { SpAtAlert } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-alert';
import { SpAtAnimation } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-animation';
import { SpAtAutocomplete } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-autocomplete';
import { SpAtAvatar } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-avatar';
import { SpAtBackdrop } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-backdrop';
import { SpAtCheckButton } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-check-button';
import { SpAtComboBox } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-combo-box';
import { SpAtConfetti } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-confetti';
import { SpAtDropdown } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-dropdown';
import { SpAtInput } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-input';
import { SpAtInputToken } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-input-token';
import { SpAtLoadButton } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-load-button';
import { SpAtLogo } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-logo';
import { SpAtMultiAutocomplete } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-multi-autocomplete';
import { SpAtProgressBar } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-progress-bar';
import { SpAtProgressIndicator } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-progress-indicator';
import { SpAtProgressLine } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-progress-line';
import { SpAtRadioButton } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-radio-button';
import { SpAtSecondTooltip } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-second-tooltip';
import { SpAtSkeleton } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-skeleton';
import { SpAtStandarProgress } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-standar-progress';
import { SpAtTag } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-tag';
import { SpAtTextArea } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-text-area';
import { SpAtToast } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-toast';
import { SpAtToggle } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-toggle';
import { SpAtToggleVisualizer } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-toggle-visualizer';
import { SpAtTooltip } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-at-tooltip';
import { SpCardsBines } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-cards-bines';
import { SpIllustration } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-illustration';
import { SpMlAcceptDocs } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-accept-docs';
import { SpMlAccessCard } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-access-card';
import { SpMlAccordion } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-accordion';
import { SpMlActivationCard } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-activation-card';
import { SpMlActiveSelector } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-active-selector';
import { SpMlAddressForm } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-address-form';
import { SpMlBasicData } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-basic-data';
import { SpMlBmActionSheet } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-bm-action-sheet';
import { SpMlBmCard } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-bm-card';
import { SpMlBmCardReverse } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-bm-card-reverse';
import { SpMlBmHalfCard } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-bm-half-card';
import { SpMlBmHeader } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-bm-header';
import { SpMlBmOtp } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-bm-otp';
import { SpMlBmSurvey } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-bm-survey';
import { SpMlBmToken } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-bm-token';
import { SpMlBmVoucher } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-bm-voucher';
import { SpMlBoxButton } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-box-button';
import { SpMlBreadcrumbs } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-breadcrumbs';
import { SpMlButtonSelector } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-button-selector';
import { SpMlCalendar } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-calendar';
import { SpMlCalendarLite } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-calendar-lite';
import { SpMlCardEnding } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-card-ending';
import { SpMlCardList } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-card-list';
import { SpMlCardPrice } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-card-price';
import { SpMlCardPromotion } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-card-promotion';
import { SpMlCardSelector } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-card-selector';
import { SpMlChartDonut } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-chart-donut';
import { SpMlCheckboxMultiple } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-checkbox-multiple';
import { SpMlChipSelector } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-chip-selector';
import { SpMlCompoundList } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-compound-list';
import { SpMlConfirmation } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-confirmation';
import { SpMlConfirmationData } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-confirmation-data';
import { SpMlContentTitle } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-content-title';
import { SpMlCountdown } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-countdown';
import { SpMlCustomerValidation } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-customer-validation';
import { SpMlDashboardCard } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-dashboard-card';
import { SpMlDateInput } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-date-input';
import { SpMlDatePicker } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-date-picker';
import { SpMlDetailDocument } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-detail-document';
import { SpMlDocumentViewer } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-document-viewer';
import { SpMlDrawer } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-drawer';
import { SpMlDynamicInput } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-dynamic-input';
import { SpMlDynamicTable } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-dynamic-table';
import { SpMlFinancialData } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-financial-data';
import { SpMlFooter } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-footer';
import { SpMlFooterLanding } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-footer-landing';
import { SpMlHeader } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-header';
import { SpMlHeaderBm } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-header-bm';
import { SpMlHeaderLanding } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-header-landing';
import { SpMlHorizontalSelector } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-horizontal-selector';
import { SpMlInfoLoader } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-info-loader';
import { SpMlLoader } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-loader';
import { SpMlLoginForm } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-login-form';
import { SpMlMapOffice } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-map-office';
import { SpMlModal } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-modal';
import { SpMlModalNormal } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-modal-normal';
import { SpMlModalOnboarding } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-modal-onboarding';
import { SpMlMoveList } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-move-list';
import { SpMlMultiAction } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-multi-action';
import { SpMlMultiSelector } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-multi-selector';
import { SpMlNotificationCard } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-notification-card';
import { SpMlOtp } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-otp';
import { SpMlOverflowMenu } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-overflow-menu';
import { SpMlPagination } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-pagination';
import { SpMlProfile } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-profile';
import { SpMlQuicksCards } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-quicks-cards';
import { SpMlResume } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-resume';
import { SpMlResumeAccordion } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-resume-accordion';
import { SpMlSearchInput } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-search-input';
import { SpMlSecondtabs } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-secondtabs';
import { SpMlShare } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-share';
import { SpMlSidebar } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-sidebar';
import { SpMlSlider } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-slider';
import { SpMlSummary } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-summary';
import { SpMlTabs } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-tabs';
import { SpMlTerms } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-terms';
import { SpMlTrackingCard } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-tracking-card';
import { SpMlUpload } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-upload';
import { SpMlUploadFile } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-upload-file';
import { SpMlVideo } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-ml-video';
import { SpPictogram } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-pictogram';
import { SpTpBv } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-tp-bv';
import { SpTpCnEmptyState } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-tp-cn-empty-state';
import { SpTpDashboard } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-tp-dashboard';
import { SpTpEmptyState } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-tp-empty-state';
import { SpTpPayments } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-tp-payments';
import { SpTpProgress } from '@npm-bbta/bbog-dig-dt-sherpa-lib/dist/custom-elements/sp-tp-progress';


const defineCustomElements = () => {
  customElements.define('sp-at-accordion-item', SpAtAccordionItem);
  customElements.define('sp-at-alert', SpAtAlert);
  customElements.define('sp-at-animation', SpAtAnimation);
  customElements.define('sp-at-autocomplete', SpAtAutocomplete);
  customElements.define('sp-at-avatar', SpAtAvatar);
  customElements.define('sp-at-backdrop', SpAtBackdrop);
  customElements.define('sp-at-check-button', SpAtCheckButton);
  customElements.define('sp-at-combo-box', SpAtComboBox);
  customElements.define('sp-at-confetti', SpAtConfetti);
  customElements.define('sp-at-dropdown', SpAtDropdown);
  customElements.define('sp-at-input', SpAtInput);
  customElements.define('sp-at-input-token', SpAtInputToken);
  customElements.define('sp-at-load-button', SpAtLoadButton);
  customElements.define('sp-at-logo', SpAtLogo);
  customElements.define('sp-at-multi-autocomplete', SpAtMultiAutocomplete);
  customElements.define('sp-at-progress-bar', SpAtProgressBar);
  customElements.define('sp-at-progress-indicator', SpAtProgressIndicator);
  customElements.define('sp-at-progress-line', SpAtProgressLine);
  customElements.define('sp-at-radio-button', SpAtRadioButton);
  customElements.define('sp-at-second-tooltip', SpAtSecondTooltip);
  customElements.define('sp-at-skeleton', SpAtSkeleton);
  customElements.define('sp-at-standar-progress', SpAtStandarProgress);
  customElements.define('sp-at-tag', SpAtTag);
  customElements.define('sp-at-text-area', SpAtTextArea);
  customElements.define('sp-at-toast', SpAtToast);
  customElements.define('sp-at-toggle', SpAtToggle);
  customElements.define('sp-at-toggle-visualizer', SpAtToggleVisualizer);
  customElements.define('sp-at-tooltip', SpAtTooltip);
  customElements.define('sp-cards-bines', SpCardsBines);
  customElements.define('sp-illustration', SpIllustration);
  customElements.define('sp-ml-accept-docs', SpMlAcceptDocs);
  customElements.define('sp-ml-access-card', SpMlAccessCard);
  customElements.define('sp-ml-accordion', SpMlAccordion);
  customElements.define('sp-ml-activation-card', SpMlActivationCard);
  customElements.define('sp-ml-active-selector', SpMlActiveSelector);
  customElements.define('sp-ml-address-form', SpMlAddressForm);
  customElements.define('sp-ml-basic-data', SpMlBasicData);
  customElements.define('sp-ml-bm-action-sheet', SpMlBmActionSheet);
  customElements.define('sp-ml-bm-card', SpMlBmCard);
  customElements.define('sp-ml-bm-card-reverse', SpMlBmCardReverse);
  customElements.define('sp-ml-bm-half-card', SpMlBmHalfCard);
  customElements.define('sp-ml-bm-header', SpMlBmHeader);
  customElements.define('sp-ml-bm-otp', SpMlBmOtp);
  customElements.define('sp-ml-bm-survey', SpMlBmSurvey);
  customElements.define('sp-ml-bm-token', SpMlBmToken);
  customElements.define('sp-ml-bm-voucher', SpMlBmVoucher);
  customElements.define('sp-ml-box-button', SpMlBoxButton);
  customElements.define('sp-ml-breadcrumbs', SpMlBreadcrumbs);
  customElements.define('sp-ml-button-selector', SpMlButtonSelector);
  customElements.define('sp-ml-calendar', SpMlCalendar);
  customElements.define('sp-ml-calendar-lite', SpMlCalendarLite);
  customElements.define('sp-ml-card-ending', SpMlCardEnding);
  customElements.define('sp-ml-card-list', SpMlCardList);
  customElements.define('sp-ml-card-price', SpMlCardPrice);
  customElements.define('sp-ml-card-promotion', SpMlCardPromotion);
  customElements.define('sp-ml-card-selector', SpMlCardSelector);
  customElements.define('sp-ml-chart-donut', SpMlChartDonut);
  customElements.define('sp-ml-checkbox-multiple', SpMlCheckboxMultiple);
  customElements.define('sp-ml-chip-selector', SpMlChipSelector);
  customElements.define('sp-ml-compound-list', SpMlCompoundList);
  customElements.define('sp-ml-confirmation', SpMlConfirmation);
  customElements.define('sp-ml-confirmation-data', SpMlConfirmationData);
  customElements.define('sp-ml-content-title', SpMlContentTitle);
  customElements.define('sp-ml-countdown', SpMlCountdown);
  customElements.define('sp-ml-customer-validation', SpMlCustomerValidation);
  customElements.define('sp-ml-dashboard-card', SpMlDashboardCard);
  customElements.define('sp-ml-date-input', SpMlDateInput);
  customElements.define('sp-ml-date-picker', SpMlDatePicker);
  customElements.define('sp-ml-detail-document', SpMlDetailDocument);
  customElements.define('sp-ml-document-viewer', SpMlDocumentViewer);
  customElements.define('sp-ml-drawer', SpMlDrawer);
  customElements.define('sp-ml-dynamic-input', SpMlDynamicInput);
  customElements.define('sp-ml-dynamic-table', SpMlDynamicTable);
  customElements.define('sp-ml-financial-data', SpMlFinancialData);
  customElements.define('sp-ml-footer', SpMlFooter);
  customElements.define('sp-ml-footer-landing', SpMlFooterLanding);
  customElements.define('sp-ml-header', SpMlHeader);
  customElements.define('sp-ml-header-bm', SpMlHeaderBm);
  customElements.define('sp-ml-header-landing', SpMlHeaderLanding);
  customElements.define('sp-ml-horizontal-selector', SpMlHorizontalSelector);
  customElements.define('sp-ml-info-loader', SpMlInfoLoader);
  customElements.define('sp-ml-loader', SpMlLoader);
  customElements.define('sp-ml-login-form', SpMlLoginForm);
  customElements.define('sp-ml-map-office', SpMlMapOffice);
  customElements.define('sp-ml-modal', SpMlModal);
  customElements.define('sp-ml-modal-normal', SpMlModalNormal);
  customElements.define('sp-ml-modal-onboarding', SpMlModalOnboarding);
  customElements.define('sp-ml-move-list', SpMlMoveList);
  customElements.define('sp-ml-multi-action', SpMlMultiAction);
  customElements.define('sp-ml-multi-selector', SpMlMultiSelector);
  customElements.define('sp-ml-notification-card', SpMlNotificationCard);
  customElements.define('sp-ml-otp', SpMlOtp);
  customElements.define('sp-ml-overflow-menu', SpMlOverflowMenu);
  customElements.define('sp-ml-pagination', SpMlPagination);
  customElements.define('sp-ml-profile', SpMlProfile);
  customElements.define('sp-ml-quicks-cards', SpMlQuicksCards);
  customElements.define('sp-ml-resume', SpMlResume);
  customElements.define('sp-ml-resume-accordion', SpMlResumeAccordion);
  customElements.define('sp-ml-search-input', SpMlSearchInput);
  customElements.define('sp-ml-secondtabs', SpMlSecondtabs);
  customElements.define('sp-ml-share', SpMlShare);
  customElements.define('sp-ml-sidebar', SpMlSidebar);
  customElements.define('sp-ml-slider', SpMlSlider);
  customElements.define('sp-ml-summary', SpMlSummary);
  customElements.define('sp-ml-tabs', SpMlTabs);
  customElements.define('sp-ml-terms', SpMlTerms);
  customElements.define('sp-ml-tracking-card', SpMlTrackingCard);
  customElements.define('sp-ml-upload', SpMlUpload);
  customElements.define('sp-ml-upload-file', SpMlUploadFile);
  customElements.define('sp-ml-video', SpMlVideo);
  customElements.define('sp-pictogram', SpPictogram);
  customElements.define('sp-tp-bv', SpTpBv);
  customElements.define('sp-tp-cn-empty-state', SpTpCnEmptyState);
  customElements.define('sp-tp-dashboard', SpTpDashboard);
  customElements.define('sp-tp-empty-state', SpTpEmptyState);
  customElements.define('sp-tp-payments', SpTpPayments);
  customElements.define('sp-tp-progress', SpTpProgress);
}
defineCustomElements();

bootstrapApplication(App, appConfig)
  .catch((err) => console.error(err));

